apiVersion: apps/v1
kind: Deployment
metadata:
  name: payments-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payments
  template:
    metadata:
      labels:
        app: payments
    spec:
      containers:
        - name: payments
          image: khanhdp95/payments
          # resources:
          #   limits:
          #     memory: 512Mi
          #     cpu: '1'
          #   requests:
          #     memory: 256Mi
          #     cpu: '0.2'
          # to create JWT_KEY, run below command
          # kubectl create secret generic jwt-secret --from-literal JWT_KEY=asdf
          env:
            - name: NATS_CLIENT_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name

            - name: NATS_URL
              value: 'http://nats-srv:4222'

            - name: NATS_CLUSTER_ID
              value: ticketing

            - name: MONGO_URI
              value: 'mongodb://payments-mongo-srv:27017/payments'

            - name: JWT_KEY
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: JWT_KEY

            - name: STRIPE_KEY
              valueFrom:
                secretKeyRef:
                  name: stripe-secret
                  key: STRIPE_KEY
---
apiVersion: v1
kind: Service
metadata:
  name: payments-srv
spec:
  selector:
    app: payments
  ports:
    - port: 3000
      targetPort: 3000
