name: tests-tickets

on:
  pull_request:
    paths:
      - 'tickets/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: cd tickets && npm i --legacy-peer-deps && npm run test:ci
